sudo: required
python: 3.6

language: C

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python3-numpy

matrix:
  include:
    - compiler: gcc
      before_script:
        - git clone https://github.com/plures/ndtypes.git
        - git clone https://github.com/plures/xnd.git
        - cd ndtypes
        - python3 setup.py install --local=$PWD/../python
        - cd ../xnd
        - python3 setup.py install --local=$PWD/../python
        - cd ..
      script:
        - python3 setup.py build
        - python3 setup.py test
