sudo: required

language: python
python:
  - 3.6


matrix:
  include:
    - compiler: gcc
      before_install:
        - pip install numpy
      before_script:
        - git clone https://github.com/plures/ndtypes.git
        - git clone https://github.com/plures/xnd.git
        - cd ndtypes
        - python3 setup.py install --local=$PWD/../python
        - cd ../xnd
        - python3 setup.py install --local=$PWD/../python
        - cd ..
      script:
        - python3 setup.py build
        - python3 setup.py test

    - language: objective-c
      os: osx
      compiler: clang
      before_install:
        - brew install python3
        - python3 -m pip install numpy numba
      before_script:
        - export CC=clang
        - git clone https://github.com/plures/ndtypes.git
        - git clone https://github.com/plures/xnd.git
        - cd ndtypes
        - python3 setup.py install --local=$PWD/../python
        - cd ../xnd
        - python3 setup.py install --local=$PWD/../python
        - cd ..
      script:
        - python3 setup.py build
        - python3 setup.py test

    - compiler: conda
      install:
        - cd ..
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
        - bash Miniconda3-latest-Linux-x86_64.sh -b
        - export PATH=$HOME/miniconda3/bin:$PATH
        - conda update --yes conda
        - conda install --yes conda-build=3.3.0
        - conda install --yes anaconda-client
        - conda install --yes numpy
        - conda install --yes numba
        - conda install --yes -c plures/label/dev ndtypes
        - conda install --yes -c plures/label/dev xnd
      script:
        - cd gumath
        - git fetch --unshallow
        - conda build .conda/libgumath -c plures/label/dev
        - conda build .conda/gumath -c plures/label/dev
        - export LIBGUMATH=`conda build --output .conda/libgumath -c plures/label/dev`
        - export GUMATH=`conda build --output .conda/gumath -c plures/label/dev`
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $LIBXND --user plures --label dev; fi
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $XND --user plures --label dev; fi

    - language: objective-c
      os: osx
      compiler: conda
      install:
        - cd ..
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
        - bash Miniconda3-latest-MacOSX-x86_64.sh -b
        - export PATH=$HOME/miniconda3/bin:$PATH
        - export CC=clang
        - conda update --yes conda
        - conda install --yes conda-build=3.3.0
        - conda install --yes anaconda-client
        - conda install --yes numpy
        - conda install --yes numba
        - conda install --yes -c plures/label/dev ndtypes
        - conda install --yes -c plures/label/dev xnd
      script:
        - cd gumath
        - git fetch --unshallow
        - conda build .conda/libgumath -c plures/label/dev
        - conda build .conda/gumath -c plures/label/dev
        - export LIBGUMATH=`conda build --output .conda/libgumath -c plures/label/dev`
        - export GUMATH=`conda build --output .conda/gumath -c plures/label/dev`
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $LIBXND --user plures --label dev; fi
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $XND --user plures --label dev; fi

env:
  global:
    - secure: "cxhvakc6xXUvK6HbA7H/zXf6mGF+Qqgp+zdUqioeeEiOOB7lj5Ygxubco55BuaB/48OyiujnwEeAy8lHiXB0gBfqlykOYrwvW+s6leqyPq+OnH3FZmEIhSsAKx0xDvH/PjPdGeWBdHTEwowof9YWSdQaJlnLeiIAMB6UbuyvLA8ytLS4Jcb+fOCnKRKs+wppT97UudlHzwXqAF/bHjDTzoDvowinRmeFoFcrgjL1+gvXWZcXMx+BO3FutLa3CCgN4J+6Oi+nzVo1vLLuHaSpdrFUHZfAG+CqlnWYVfC7lloFvFotNCMOz/0vSfrjtOWQ5T68l5XczLS0Q6dyS0L27fIuZYxGhqk0K72uhMZB0n80cVnZ4RDAnP3fvLtk43u8iB436pmtHOqU+EcvAmI1flK613s8k7UYtlc4t7I+T6E6065GuxLo/vbJwdmVF6Z5SICrpCD0WDlldKyLG7+/qd+7oca4BONzdfa7qjBF05NgFWSvGeWmf+wPDRPY7q/9yMAh5Z7Bi7FgOFTSklOXOch8v70D4+wX1aUUZ9qx+kiZYI8/djUIEPnqS54gXAyRfraDN/VuY3yk0aPgXZgCXzr8kOXxbyF8o+9y0sUZ26qN0cRegrrhNVZ1BYYOnsDAS7QPF447ZQIIaqYVuhh0+wdiTJjXqyGgsa9PuuCFAL8="
